load states and solve manually
ros-planning/moveit_calibration pull request #53
Opened 2020-12-18 19:54 UTC by christian-rauch

This adds a button to load states and a button to call the solver manually. Fixes #52 .

2020-12-20 18:43 UTC, JStech requested changes
Thanks for the contribution! Could you please add a screenshot of the updated UI?

2020-12-20 18:43 UTC, JStech commented on moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
> +    QMessageBox::warning(this, calibration_solver_->currentText(), "Solver failed. Check stdout.");
Since the error output is sent to the ROS console, maybe say 'Check console output' instead?

2020-12-21 11:26 UTC, christian-rauch commented
I added a screenshot of the GUI and changed the warning message to `Solver failed. Check ROS console output.`.

2020-12-21 21:01 UTC, JStech approved these changes

2020-12-21 21:22 UTC, JStech requested changes

2020-12-21 21:22 UTC, JStech commented on moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
> +    QMessageBox::warning(this, calibration_solver_->currentText(), "Solver failed. Check ROS console output.");
On second thought, `solveCameraRobotPose` already displays a warning dialog if it fails for any reason. I think this function could just call it, and ignore the return value. (Sorry I didn't figure this out the first time.)

2021-01-07 16:27 UTC, christian-rauch commented on moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
> +    QMessageBox::warning(this, calibration_solver_->currentText(), "Solver failed. Check ROS console output.");
I change the code path there. The solver can be successful (i.e. `res==true`), but it will still fail if the frames are not given (e.g. if the robot and its TF are not running). In the latter case, it just prints the solution to the log so it can still be used without frames.

2021-01-11 18:18 UTC, christian-rauch commented on moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
> +    QMessageBox::warning(this, calibration_solver_->currentText(), "Solver failed. Check ROS console output.");
I changed the logic to only change a single `Solver Failed` message box with wither a solver failure or failure because of missing frame names.

2021-01-12 00:01 UTC, JStech approved these changes
Thanks for the updates--looks good to me. There was one change that looks accidental.

2021-01-12 00:14 UTC, christian-rauch commented on moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_control_widget.h
> + *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
I actually think that `sensorPoseUpdate` was accidentally pasted into the source file while the cursor was within the license text.

The license statement
> IN NO EVENT SHALL THEsensorPoseUpdate COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE

 makes no sense to me. I am pretty sure the license does not only cover the method `sensorPoseUpdate` :-)

This should very likely be "THE COPYRIGHT OWNER".

2021-01-12 03:32 UTC, JStech commented on moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_control_widget.h
> + *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
Oh, my brain just got this backwards. You're fixing the mistake. My bad.

2021-01-12 03:33 UTC, merged